<script src="{{ asset('assets/dashboard/js/jquery.min.js') }}"></script>
<script src="{{ asset('assets/dashboard/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/dashboard/js/bootstrap-select.min.js') }}"></script>
<!-- <script src="//cdn.datatables.net/2.1.4/js/dataTables.min.js"></script> -->
<!-- <script src="https://cdn.ckeditor.com/ckeditor5/39.0.0/classic/ckeditor.js"></script> -->
<script src="{{ asset('assets/dashboard/js/echarts.min.js') }}"></script>
<script src="{{ asset('assets/dashboard/js/main.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
